# Generated by Django 4.2.11 on 2024-03-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja pozarządowa', 'Organizacja pozarządowa'), ('zbiorka lokalna', 'Zbiorka lokalna')], default='fundacja', max_length=30),
        ),
    ]
